- hosts: localhost
  become: yes
  vars:
    jenkins_hostname: ec2-3-86-199-237.compute-1.amazonaws.com
    docker_users:
    - jenkins
  roles:
    - role: geerlingguy.jenkins
    - role: geerlingguy.docker